#ifndef DIDPDS_VERSION_INCLUDED
#define DIDPDS_VERSION_INCLUDED

#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str) MAKE_STR_HELPER(a_str)

#if SKYRIM
#define DIDPDS_DLL_NAME "DarkId.Papyrus.DebugServer.Skyrim.dll"
#elif FALLOUT
#define DIDPDS_DLL_NAME "DarkId.Papyrus.DebugServer.Fallout4.dll"
#endif

#ifndef DIDPDS_VERSION_MAJOR
#define DIDPDS_VERSION_MAJOR 0
#endif

#ifndef DIDPDS_VERSION_MINOR
#define DIDPDS_VERSION_MINOR 0
#endif

#ifndef DIDPDS_VERSION_PATCH
#define DIDPDS_VERSION_PATCH 0
#endif

#ifndef DIDPDS_VERSION_BUILD
#define DIDPDS_VERSION_BUILD 0
#endif

#define DIDPDS_VERSION_WIN_VERSTRING MAKE_STR(DIDPDS_VERSION_MAJOR) "." MAKE_STR(DIDPDS_VERSION_MINOR) "." MAKE_STR(DIDPDS_VERSION_PATCH) "." MAKE_STR(DIDPDS_VERSION_BUILD)
#define DIDPDS_VERSION_SEMVER MAKE_STR(DIDPDS_VERSION_MAJOR) "." MAKE_STR(DIDPDS_VERSION_MINOR) "." MAKE_STR(DIDPDS_VERSION_PATCH)

#endif // DIDPDS_VERSION_INCLUDED
