#ifndef	DIDPDS_VERSION_INCLUDED
#define DIDPDS_VERSION_INCLUDED

#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str) MAKE_STR_HELPER(a_str)

#if SKYRIM
#define DIDPDS_DLL_NAME "DarkId.Papyrus.DebugServer.Skyrim.dll"
#elif FALLOUT
#define DIDPDS_DLL_NAME "DarkId.Papyrus.DebugServer.Fallout4.dll"
#endif

// Manual update for now
#define DIDPDS_VERSION_MAJOR	1

#define DIDPDS_VERSION_MINOR	57

#define DIDPDS_VERSION_PATCH	0

// Just manually update DIDPDS_VERSION_BETA for now
#define DIDPDS_VERSION_BETA   1

#define DIDPDS_VERSION_WIN_VERSTRING	MAKE_STR(DIDPDS_VERSION_MAJOR) "." MAKE_STR(DIDPDS_VERSION_MINOR) "." MAKE_STR(DIDPDS_VERSION_PATCH) "." MAKE_STR(DIDPDS_VERSION_BETA)
#if DIDPDS_VERSION_BETA == 0
#define DIDPDS_VERSION_SEMVER  MAKE_STR(DIDPDS_VERSION_MAJOR) "." MAKE_STR(DIDPDS_VERSION_MINOR) "." MAKE_STR(DIDPDS_VERSION_PATCH)
#else
#define DIDPDS_VERSION_SEMVER  MAKE_STR(DIDPDS_VERSION_MAJOR) "." MAKE_STR(DIDPDS_VERSION_MINOR) "." MAKE_STR(DIDPDS_VERSION_PATCH) "-beta" MAKE_STR(DIDPDS_VERSION_BETA)
#endif

#endif //DIDPDS_VERSION_INCLUDED
