<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>comment</key>
    <string></string>
    <key>fileTypes</key>
    <array>
        <string>psc</string>
    </array>
    <key>firstLineMatch</key>
    <string>(?i)^scriptname</string>
    <key>foldingStartMarker</key>
    <string>(?i)^\s*(if|while|property|struct|group|state|event|(\S+\s+)?function)</string>
    <key>foldingStopMarker</key>
    <string>(?i)^\s*(endif|endwhile|endproperty|endstruct|endgroup|endstate|endevent|endfunction)</string>
    <key>name</key>
    <string>papyrus</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>include</key>
            <string>#quoted-string</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>;/</string>
            <key>end</key>
            <string>/;</string>
            <key>name</key>
            <string>comment.block.papyrus</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(;).*$\n?</string>
            <key>name</key>
            <string>comment.line.semicolon.papyrus</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>{</string>
            <key>end</key>
            <string>}</string>
            <key>name</key>
            <string>comment.documentation.papyrus</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>(?i)^\s*(scriptname)\s+([:\w]+)(\s+(extends)\s+(\S+))?</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>support.type.other.scriptname-declaration.papyrus</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.type.scriptname.papyrus</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>keyword.language.extends.papyrus</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>entity.other.inherited-class.papyrus</string>
                </dict>
            </dict>
            <key>end</key>
            <string>\n</string>
            <key>name</key>
            <string>meta.scriptname-declaration.papyrus</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>;([^\n]*)</string>
                    <key>name</key>
                    <string>comment.line.semicolon.papyrus</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(?i)(?:\s+|(?&lt;=/;))(conditional|default|hidden|native|const)(?=\s|;|$)</string>
                    <key>name</key>
                    <string>keyword.language.script-flag.papyrus</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>(?i)(property)\s+(\S+)</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.other.property.papyrus</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>variable.other.property.papyrus</string>
                </dict>
            </dict>
            <key>end</key>
            <string>\n</string>
            <key>name</key>
            <string>meta.property.papyrus</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#constants</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#quoted-string</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>;([^\n]*)</string>
                    <key>name</key>
                    <string>comment.line.semicolon.papyrus</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(?i)\b(auto|autoreadonly|const|conditional|mandatory|hidden)\b</string>
                    <key>name</key>
                    <string>keyword.language.property-flag.papyrus</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\=</string>
                    <key>name</key>
                    <string>keyword.operator.assignment.papyrus</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>(?i)\b(function|event)\s+([^\(]*)\(</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.control.functionstart.papyrus</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.papyrus</string>
                </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>name</key>
            <string>meta.function.papyrus</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#params</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(auto\s+)?(state)\s+(.*)\n</string>
            <key>name</key>
            <string>meta.state.papyrus</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.language.state-flag.papyrus</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>keyword.control.statestart.papyrus</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.section.papyrus</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(struct)\s+(.*)\n</string>
            <key>name</key>
            <string>meta.struct.papyrus</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.control.structstart.papyrus</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.struct.papyrus</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(group)\s+(\S*)\s*(CollapsedOnRef|CollapsedOnBase|Collapsed)?\s*\n</string>
            <key>name</key>
            <string>meta.group.papyrus</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.control.groupstart.papyrus</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.section.papyrus</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>variable.language.groupflag.papyrus</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>include</key>
            <string>#constants</string>
        </dict>
        <dict>
            <key>match</key>
            <string>&amp;&amp;|\|\||\=\=|!\=|&lt;\=|&gt;\=|&gt;|&lt;</string>
            <key>name</key>
            <string>keyword.operator.logical.papyrus</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\+|\-|\*|/|!|%</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.papyrus</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\=|\+\=|-\=|\*\=|/\=|%\=</string>
            <key>name</key>
            <string>keyword.operator.assignment.papyrus</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(if|else|elseif|endif|while|endwhile|return)\b</string>
            <key>name</key>
            <string>keyword.control.flow.papyrus</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(import)\b</string>
            <key>name</key>
            <string>keyword.control.import.papyrus</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(new)\b</string>
            <key>name</key>
            <string>keyword.control.new.papyrus</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(global|hidden|native|const|conditional)\b</string>
            <key>name</key>
            <string>storage.modifier.papyrus</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(self|parent)\b</string>
            <key>name</key>
            <string>variable.language.papyrus</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(endstate)\b</string>
            <key>name</key>
            <string>keyword.control.stateend.papyrus</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(endgroup)\b</string>
            <key>name</key>
            <string>keyword.control.groupend.papyrus</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(endstruct)\b</string>
            <key>name</key>
            <string>keyword.control.structend.papyrus</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(endfunction)\b</string>
            <key>name</key>
            <string>keyword.control.functionend.papyrus</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(endevent)\b</string>
            <key>name</key>
            <string>keyword.control.eventend.papyrus</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(endproperty)\b</string>
            <key>name</key>
            <string>keyword.control.propertyend.papyrus</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#base-types</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#class-types</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#builtin-funcs</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#newline-escape</string>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>base-types</key>
        <dict>
            <key>match</key>
            <string>(?i)\b(int|string|float|bool|var)\b</string>
            <key>name</key>
            <string>storage.type.papyrus</string>
        </dict>
        <key>constants</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\b(?i:(\d+\.\d*(e[\-\+]?\d+)?))(?=[^a-zA-Z_])</string>
                    <key>name</key>
                    <string>constant.numeric.float.papyrus</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b([1-9]+[0-9]*|0)</string>
                    <key>name</key>
                    <string>constant.numeric.integer.papyrus</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(?i)\b(true|false|none)\b</string>
                    <key>name</key>
                    <string>constant.language.bool.papyrus</string>
                </dict>
            </array>
        </dict>
        <key>quoted-string</key>
        <dict>
            <key>name</key>
            <string>string.quoted.double.papyrus</string>
            <key>begin</key>
            <string>&quot;</string>
            <key>end</key>
            <string>[&quot;\n]</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string-character-escape</string>
              </dict>
            </array>
        </dict>
        <key>string-character-escape</key>
        <dict>
            <key>name</key>
            <string>constant.character.escape.papyrus</string>
            <key>match</key>
            <string>\\[nt\\&quot;]?</string>
        </dict>
        <key>newline-escape</key>
        <dict>
            <key>match</key>
            <string>\\(?=\s*\n)</string>
            <key>name</key>
            <string>constant.character.escape.papyrus</string>
        </dict>
        <key>params</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#constants</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#quoted-string</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(?:\G\s*|,\s*)([\w\[\]:]+)\s+(\w+)\b(?:\s*(=))?</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>storage.type.variable.papyrus</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>variable.parameter.papyrus</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.operator.assignment.papyrus</string>
                        </dict>
                    </dict>
                    <key>name</key>
                    <string>meta.parameter.papyrus</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#newline-escape</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>[^\s\)]+?</string>
                    <key>name</key>
                    <string>invalid.illegal.function.papyrus</string>
                </dict>
            </array>
        </dict>
    </dict>
    <key>scopeName</key>
    <string>source.papyrus</string>
    <key>uuid</key>
    <string>9222FE11-FBF1-49B0-B158-FD20C68E95AF</string>
</dict>
</plist>